---

# This code is designed to connect to your Classic BIG-IP and disable a waf policy, currently its hard coded in vars but one could use a payload to resolve this
# this is also looking for Hosts F5 this could be modified as well for any other reason.

- name: Change ASM Policy Enforcement Mode
  hosts: f5
  connection: local

  vars:
    waf_policy: "WAF-POLICY"
    provider:
      server: "{{ ansible_host }}"
      user: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      validate_certs: false
      no_f5_teem: true
      server_port: 443
  tasks:
    - name: Change ASM Policy to Transparent
      f5networks.f5_modules.bigip_command:
        commands:
          - modify asm policy "{{ waf_policy }}" blocking-mode disabled
          - publish asm policy "{{ waf_policy }}"
        provider: "{{ provider }}"
